# nodeLinker: node-modules

# packageExtensions:
#   next@*:
#     dependencies:
#       "@next/swc-linux-arm-gnueabihf": latest
#       "@next/swc-wasm-nodejs": latest

yarnPath: .yarn/releases/yarn-3.6.1.cjs
