# nodeLinker: node-modules

packageExtensions:
  # workbox-webpack-plugin@^6.5.4:
  #   peerDependencies:
  #     webpack: "^4.4.0 || ^5.9.0"
  next-pwa@^5.6.0:
    peerDependencies:
      "@babel/core": "^7.0.0"
      "webpack": ">=2"

#   next@*:
#     dependencies:
#       "@next/swc-linux-arm-gnueabihf": latest
#       "@next/swc-wasm-nodejs": latest

yarnPath: .yarn/releases/yarn-3.6.1.cjs
